language: python
dist: trusty
sudo: false

python:
- "2.7"
- "3.2"

before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes
- conda install -q pip openblas numpy scipy
- "pip install -q nose"
- "pip install 'coverage<4'"  # After 4, there is some issue when using python 3.2
- git clone git@github.com:NLeSC/mcfly.git mcfly
- "pip install -qr mcfly/requirements.txt"

install:
- "echo done"

# command to run tests, e.g. python setup.py test
script:
- nosetests --with-coverage --cover-package=mcfly-tutorial

after_script:
- "pip install scrutinizer-ocular"
- "ocular"
